---
- name: Deploy Application into EKS cluster
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Apply Kubernetes Deployment
      ansible.builtin.command:
        cmd: kubectl apply -f /home/runner/work/ansible_k8s_github_actions_project-karthik-patel/ansible_k8s_github_actions_project-karthik-patel/Ansible/k8s_deployment.yaml
